// Имена инструментов. Claude подписывает вызов инструмента локального расширения его
// именем: «send_message» → «Send message», а поле title игнорирует. Поэтому имена —
// действия без приставки telegram_: название коннектора и значок и так стоят рядом.
// Так же названы инструменты коннектора Bybit.
export const TOOL = {
  status: 'connector_status',
  login: 'open_login_page',
  listChats: 'list_chats',
  listFolders: 'list_chat_folders',
  getChat: 'get_chat_info',
  searchChats: 'search_chats',
  getMembers: 'get_chat_members',
  listContacts: 'list_contacts',
  joinChat: 'join_chat',
  leaveChat: 'leave_chat',
  getMessages: 'get_messages',
  searchMessages: 'search_messages',
  subscribe: 'subscribe_to_messages',
  sendMessage: 'send_message',
  editMessage: 'edit_message',
  forwardMessages: 'forward_messages',
  deleteMessages: 'delete_messages',
  react: 'react_to_message',
  markRead: 'mark_as_read',
  pinMessage: 'pin_message',
  votePoll: 'vote_in_poll',
  sendFile: 'send_file',
  downloadMedia: 'download_media',
  transcribeVoice: 'transcribe_voice',
  pressButton: 'press_button',
  startBot: 'start_bot',
  inlineQuery: 'get_inline_results',
  sendInlineResult: 'send_inline_result',
  manageChat: 'manage_chat',
  createChat: 'create_chat',
  updateProfile: 'update_profile',
  manageContact: 'manage_contact',
  searchApi: 'search_api_methods',
  describeApi: 'describe_api_method',
  callApi: 'send_api_request',
};
